NEWS.md
R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R

Add chunks id

---

R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R

part of https://github.com/insightsengineering/teal.reporter/issues/88, https://github.com/insightsengineering/teal.reporter/issues/120 and https://github.com/insightsengineering/teal.slice/issues/56
Use UI and SRV from simple_reporter
Remove adding title for Filter state and Show R code

reporter cleaning

---

R/tm_g_heat_bygrade.R
man/tm_g_heat_bygrade.Rd

Closes #169 - test tm_g_heat_bygrade roxygen example

fix example

---

R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R

Part of https://github.com/insightsengineering/teal.code/issues/67
along with https://github.com/insightsengineering/teal.code/pull/68

updates after teal.code changes

---

NEWS.md
R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R
man/tm_g_ae_oview.Rd
man/tm_g_ae_sub.Rd
man/tm_g_butterfly.Rd
man/tm_g_events_term_id.Rd
man/tm_g_heat_bygrade.Rd
man/tm_g_patient_profile.Rd
man/tm_g_spiderplot.Rd
man/tm_g_swimlane.Rd
man/tm_g_waterfall.Rd

Part of https://github.com/insightsengineering/teal.code/issues/34 see https://github.com/insightsengineering/teal.code/pull/74
I also replaced dontrun with if (interactive()) as it was annoying me so much not being able to run the apps in RSrudio easily

rename to qenv

---

DESCRIPTION
NEWS.md
R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R

Stage 1 of:
https://github.com/insightsengineering/teal.osprey/issues/158
-  shinyvalidate::sv_required introduced
-  non equal condition checked for ae_oview (proporsal)
TODO:
- number of levels in factor
- variable present in dataset
- selected levels present in variable
- filtering producing empty dataset
- and a number of other checks
- lookout for missed checks

128 replace validate@main

---

NEWS.md
R/tm_g_heat_bygrade.R

Closes #175 
Note this is going into teal_refactor@main

fix conmed

---

.github/workflows/check.yaml
NEWS.md
R/argument_convention.R
R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R
man/argument_convention.Rd
man/tm_g_ae_oview.Rd
man/tm_g_ae_sub.Rd
man/tm_g_butterfly.Rd
man/tm_g_events_term_id.Rd
man/tm_g_heat_bygrade.Rd
man/tm_g_patient_profile.Rd
man/tm_g_spiderplot.Rd
man/tm_g_swimlane.Rd
man/tm_g_waterfall.Rd

Part of https://github.com/insightsengineering/teal/issues/731

Teal refactor

---

NEWS.md
R/tm_g_spiderplot.R

Fixes #[13](https://github.com/insightsengineering/teal.osprey/issues/13)

x and y facets different validation

---

R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R

linked to insightsengineering/teal#769

fix after teal

---

.lintr
R/tm_g_ae_sub.R

```r
within({
ADSL <- rADSL
ADAE <- rADAE
})
datanames(data) <- c("ADSL", "ADAE")
app <- init(
data = data,
tm_g_ae_sub(
label = "AE by Subgroup",
dataname = "ADAE",
arm_var = teal.transform::choices_selected(
selected = "ACTARMCD",
choices = c("ACTARM", "ACTARMCD")
),
group_var = teal.transform::choices_selected(
selected = c("SEX", "REGION1", "RACE"),
choices = c("SEX", "REGION1", "RACE")
),
plot_height = c(600, 200, 2000)
)
)
)
if (interactive()) {
shinyApp(app$ui, app$server)
}
```

`tdata` to `teal_data` - `tm_g_ae_sub`

---

R/tm_g_butterfly.R

```r
within({
library(dplyr)
set.seed(23)
ADSL <- rADSL
ADAE <- rADAE
ADSL <- mutate(ADSL, DOSE = paste(sample(1:3, n(), replace = TRUE), "UG"))
ADAE <- mutate(
ADAE,
flag1 = ifelse(AETOXGR == 1, 1, 0),
flag2 = ifelse(AETOXGR == 2, 1, 0),
flag3 = ifelse(AETOXGR == 3, 1, 0),
flag1_filt = rep("Y", n())
)
})
datanames(data) <- c("ADSL", "ADAE")
app <- init(
data = data,
tm_g_butterfly(
label = "Butterfly Plot",
dataname = "ADAE",
right_var = choices_selected(
selected = "SEX",
choices = c("SEX", "ARM", "RACE")
),
left_var = choices_selected(
selected = "RACE",
choices = c("SEX", "ARM", "RACE")
),
category_var = choices_selected(
selected = "AEBODSYS", …
```

`tdata` to `teal_data` - `tm_g_butterfly`

---

R/tm_g_events_term_id.R

```r
within({
ADSL <- rADSL
ADAE <- rADAE
})
datanames(data) <- c("ADSL", "ADAE")
app <- init(
data = data,
tm_g_events_term_id(
label = "Common AE",
dataname = "ADAE",
term_var = choices_selected(
selected = "AEDECOD",
choices = c(
"AEDECOD", "AETERM",
"AEHLT", "AELLT", "AEBODSYS"
)
),
arm_var = choices_selected(
selected = "ACTARMCD",
choices = c("ACTARM", "ACTARMCD")
),
plot_height = c(600, 200, 2000)
)
)
)
if (interactive()) {
shinyApp(app$ui, app$server)
}
```

`tdata` to `teal_data` - `tm_g_events_term_id`

---

R/tm_g_patient_profile.R

```r
within({
ADSL <- rADSL
ADAE <- rADAE %>% mutate(ASTDT = as.Date(ASTDTM), AENDT = as.Date(AENDTM))
ADCM <- rADCM %>% mutate(ASTDT = as.Date(ASTDTM), AENDT = as.Date(AENDTM))
ADCM <- ADCM %>%
select(-starts_with("ATC")) %>%
unique()
ADRS <- rADRS %>% mutate(ADT = as.Date(ADTM))
ADEX <- rADEX %>% mutate(ASTDT = as.Date(ASTDTM), AENDT = as.Date(AENDTM))
ADLB <- rADLB %>% mutate(ADT = as.Date(ADTM), LBSTRESN = as.numeric(LBSTRESC))
})
datanames(data) <- c("ADSL", "ADAE", "ADCM", "ADRS", "ADEX", "ADLB")
ADSL <- data[["ADSL"]]
app <- init(
data = data,
tm_g_patient_profile(
label = "Patient Profile Plot",
patient_id = choices_selected(
choices = …
```

`tdata` to `teal_data` - `tm_g_patient_profile`

---

R/tm_g_swimlane.R

```r
data <- teal.data::cdisc_data() |>
within(library(dplyr)) |>
within(library(nestcolor)) |>
within(ADSL <- osprey::rADSL %>%
dplyr::mutate(TRTDURD = as.integer(TRTEDTM - TRTSDTM) + 1) %>%
dplyr::filter(STRATA1 == "A" & ARMCD == "ARM A")) |>
within(ADRS <- osprey::rADRS) |>
within(ADRS <- ADRS %>%
dplyr::filter(PARAMCD == "LSTASDI" & DCSREAS == "Death") %>%
mutate(AVALC = DCSREAS, ADY = EOSDY) %>%
base::rbind(ADRS %>% dplyr::filter(PARAMCD == "OVRINV" & AVALC != "NE")) %>%
arrange(USUBJID))
teal.data::datanames(data) <- c("ADSL", "ADRS")
teal.data::join_keys(data) <- teal.data::default_cdisc_join_keys[teal.data::datanames(data)]
ADSL <- data[["ADSL"]]
ADRS <- data[["ADRS"]]
app <- teal::init(
data = data,
modules = teal::modules(
tm_g_swimlane(
label = "Swimlane Plot", …
```

`tdata` to `teal_data` - `tm_g_swimlane`

---

R/tm_g_heat_bygrade.R

```r
within({
library(dplyr)
ADSL <- rADSL %>% slice(1:30)
ADEX <- rADEX %>% filter(USUBJID %in% ADSL$USUBJID)
ADAE <- rADAE %>% filter(USUBJID %in% ADSL$USUBJID)
ADCM <- rADCM %>% filter(USUBJID %in% ADSL$USUBJID)
ADCM <- ADCM %>%
select(-starts_with("ATC")) %>%
unique()
add_visit <- function(data_need_visit) {
visit_dates <- ADEX %>%
filter(PARAMCD == "DOSE") %>%
distinct(USUBJID, AVISIT, ASTDTM) %>%
group_by(USUBJID) %>%
arrange(ASTDTM) %>%
mutate(next_vis = lead(ASTDTM), is_last = ifelse(is.na(next_vis), TRUE, FALSE)) %>%
rename(this_vis = ASTDTM)
data_visit <- data_need_visit %>%
select(USUBJID, ASTDTM) %>%
left_join(visit_dates, by = "USUBJID") %>%
filter(ASTDTM > this_vis & (ASTDTM < next_vis | is_last == TRUE)) %>% …
```

`tdata` to `teal_data` - `tm_g_heat_bygrade`

---

R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R

part of https://github.com/insightsengineering/teal.code/pull/176

`get_code` to return concatenated code string

---

R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_waterfall.R
R/utils.R
man/get_choices.Rd

this is part of https://github.com/insightsengineering/coredev-tasks/issues/567
Here bugs are resolved found here

Fixing bugs

---

.github/workflows/scheduled.yaml

Similar to https://github.com/insightsengineering/teal.modules.general/pull/830/files
Companion to that allows to use older MultiAssayExperiment and older SummarizedExperiment 
More explanation in here https://github.com/insightsengineering/teal.slice/pull/637#issuecomment-2607373951
https://github.com/insightsengineering/teal/pull/1460
https://github.com/insightsengineering/teal.slice/pull/637

relax CI pipelines assumptions

---

DESCRIPTION
R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R

Part of https://github.com/insightsengineering/coredev-tasks/issues/650

Use the the new add button for adding a card

---

DESCRIPTION
NEWS.md
R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R
man/tm_g_ae_oview.Rd
man/tm_g_butterfly.Rd
man/tm_g_heat_bygrade.Rd
man/tm_g_patient_profile.Rd
man/tm_g_spiderplot.Rd
man/tm_g_swimlane.Rd
man/tm_g_waterfall.Rd

Related to https://github.com/insightsengineering/coredev-tasks/issues/646.
Fixes  #311
- prefix `waiver()` with `{ggplot2}`

Update modules' code for reproducibility

---

NEWS.md
R/tm_g_ae_oview.R
R/tm_g_ae_sub.R
R/tm_g_butterfly.R
R/tm_g_decorate.R
R/tm_g_events_term_id.R
R/tm_g_heat_bygrade.R
R/tm_g_patient_profile.R
R/tm_g_spiderplot.R
R/tm_g_swimlane.R
R/tm_g_waterfall.R
R/utils.R
man/label_aevar.Rd
man/plot_decorate_output.Rd
man/quick_filter.Rd
man/srv_g_decorate.Rd
man/tm_g_ae_oview.Rd
man/tm_g_ae_sub.Rd
man/tm_g_butterfly.Rd
man/tm_g_events_term_id.Rd
man/tm_g_heat_bygrade.Rd
man/tm_g_patient_profile.Rd
man/tm_g_spiderplot.Rd
man/tm_g_swimlane.Rd
man/tm_g_waterfall.Rd
man/ui_g_decorate.Rd

Part of https://github.com/insightsengineering/coredev-tasks/issues/649
Removed stable badges + hard deprecated one function.

Update lifecycle badges

---

DESCRIPTION
NEWS.md

Fixes #301 
* Update DESCRIPTION and NEWS
* vbump teal.* packages
* Remove `Remotes` entries

[skip vbump] upversion 0.3.0
