DESCRIPTION, R/tm_g_ae_oview.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, README.md, man/tm_g_ae_oview.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd
Part of https://github.com/insightsengineering/coredev-tasks/issues/334
=> fix as cran

DESCRIPTION, NEWS.md, R/tm_g_ae_oview.R, R/tm_g_ae_sub.R, R/tm_g_butterfly.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_spiderplot.R, R/tm_g_swimlane.R, R/tm_g_waterfall.R, README.md, man/tm_g_butterfly.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd, man/tm_g_swimlane.Rd, man/tm_g_waterfall.Rd
Closes [this issue](https://github.com/insightsengineering/teal.osprey/issues/185)
Following the introduction of `validate_inputs` to `teal` by [#199](https://github.com/insightsengineering/teal/pull/786),
this PR:
+ changes all possible input validations from `validate` calls to `shinyvalidate` input validators
+ passes all validators to `validate_input` funcitons
=> `shinyvalidate` improvements

.github/workflows/check.yaml, DESCRIPTION, NEWS.md, R/tm_g_ae_oview.R, R/tm_g_ae_sub.R, R/tm_g_butterfly.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_spiderplot.R, README.md, man/tm_g_ae_oview.Rd, man/tm_g_ae_sub.Rd, man/tm_g_butterfly.Rd, man/tm_g_events_term_id.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd, man/tm_g_spiderplot.Rd, staged_dependencies.yaml
closes https://github.com/insightsengineering/teal.osprey/issues/213 https://github.com/insightsengineering/teal.osprey/issues/204
see also:
- https://github.com/insightsengineering/scda/pull/125
- https://github.com/insightsengineering/scda.2022/pull/123
=> Decouple scda

R/tm_g_ae_oview.R, R/tm_g_ae_sub.R, R/tm_g_butterfly.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_spiderplot.R, R/tm_g_swimlane.R, R/tm_g_waterfall.R
https://github.com/insightsengineering/teal/issues/864
=> Move TealReportCard to teal

DESCRIPTION, NEWS.md
Releasing 0.1.16
Linking with:
https://github.com/insightsengineering/nestdevs-tasks/issues/25
=> release 0.1.16 [skip vbump] [skip spelling]

DESCRIPTION, NEWS.md, R/tm_g_ae_oview.R, R/tm_g_ae_sub.R, R/tm_g_butterfly.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_spiderplot.R, R/tm_g_swimlane.R, R/tm_g_waterfall.R, man/tm_g_ae_oview.Rd, man/tm_g_ae_sub.Rd, man/tm_g_butterfly.Rd, man/tm_g_events_term_id.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd, man/tm_g_spiderplot.Rd, man/tm_g_swimlane.Rd, man/tm_g_waterfall.Rd
Closes #231 
Modified example apps to use the following pattern:
1. create `cdisc_data`
2. use within to evaluate code
3. set datanames manually (enumerate datasets)
4. set join keys automatically with `default_cdisc_join_keys[datanames(data)]`
5. assign datasets in global where applicable
6. create app
7. run app
Removed all package prefixes in examples.
=> 78 simplify joinkeys@main

R/tm_g_spiderplot.R
```r
within({
ADSL <- rADSL
ADTR <- rADTR
})
datanames(data) <- c("ADSL", "ADTR")
app <- init(
data = data,
tm_g_spiderplot(
label = "Spider plot",
dataname = "ADTR",
paramcd = choices_selected(
choices = "SLDINV",
selected = "SLDINV"
),
x_var = choices_selected(
choices = "ADY",
selected = "ADY"
),
y_var = choices_selected(
choices = c("PCHG", "CHG", "AVAL"),
selected = "PCHG"
),
marker_var = choices_selected(
choices = c("SEX", "RACE", "USUBJID"),
selected = "SEX"
),
line_colorby_var = choices_selected(
choices = c("SEX", "USUBJID", "RACE"),
selected = "SEX"
),
xfacet_var = choices_selected(
choices = c("SEX", "ARM"),
selected = "SEX"
),
yfacet_var = …
```
=> `tdata` to `teal_data` - `tm_g_spiderplot`

R/tm_g_waterfall.R
```r
within({
ADSL <- rADSL
ADRS <- rADRS
ADTR <- rADTR
ADSL$SEX <- factor(ADSL$SEX, levels = unique(ADSL$SEX))
})
datanames(data) <- c("ADSL", "ADTR", "ADRS")
app <- init(
data = data,
tm_g_waterfall(
label = "Waterfall",
dataname_tr = "ADTR",
dataname_rs = "ADRS",
bar_paramcd = choices_selected(c("SLDINV"), "SLDINV"),
bar_var = choices_selected(c("PCHG", "AVAL"), "PCHG"),
bar_color_var = choices_selected(c("ARMCD", "SEX"), "ARMCD"),
bar_color_opt = NULL,
sort_var = choices_selected(c("ARMCD", "SEX"), NULL),
add_label_var_sl = choices_selected(c("SEX", "EOSDY"), NULL),
add_label_paramcd_rs = choices_selected(c("BESRSPI", "OBJRSPI"), NULL), …
```
=> `tdata` to `teal_data` - `tm_g_waterfall`

DESCRIPTION, inst/WORDLIST, man/teal.osprey.Rd, tests/testthat/test-utils.R
=> Append `testthat` prefix in tests

DESCRIPTION, R/teal.osprey.R, man/argument_convention.Rd, man/teal.osprey.Rd, man/tm_g_ae_oview.Rd, man/tm_g_ae_sub.Rd, man/tm_g_butterfly.Rd, man/tm_g_events_term_id.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd, man/tm_g_spiderplot.Rd, man/tm_g_swimlane.Rd, man/tm_g_waterfall.Rd
Part of https://github.com/insightsengineering/coredev-tasks/issues/506
=> Fix pkgdown redirect

.Rbuildignore, DESCRIPTION, R/argument_convention.R, R/teal.osprey.R, R/tm_g_butterfly.R, R/tm_g_decorate.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_swimlane.R, R/tm_g_waterfall.R, R/utils.R, README.md, man/shared_params.Rd, man/srv_g_decorate.Rd, man/teal.osprey-package.Rd, man/tm_g_butterfly.Rd, man/tm_g_events_term_id.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd, man/tm_g_spiderplot.Rd, man/tm_g_swimlane.Rd, man/tm_g_waterfall.Rd, man/ui_g_decorate.Rd
part of https://github.com/insightsengineering/nestdevs-tasks/issues/52
- standardise optional notation 
- updated roxygen tags
=> 52 standardise optional notation

DESCRIPTION, NEWS.md, R/tm_g_ae_oview.R, R/tm_g_ae_sub.R, R/tm_g_butterfly.R, R/tm_g_decorate.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_spiderplot.R, R/tm_g_swimlane.R, R/tm_g_waterfall.R
Similar to 
https://github.com/insightsengineering/teal.modules.general/pull/750
https://github.com/insightsengineering/teal.modules.clinical/issues/227
=> 239 utilize `logger::log_shiny_input_change`

DESCRIPTION, R/tm_g_ae_oview.R, R/tm_g_ae_sub.R, R/tm_g_butterfly.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_spiderplot.R, R/tm_g_swimlane.R, R/tm_g_waterfall.R, R/zzz.R, man/tm_g_ae_oview.Rd, man/tm_g_ae_sub.Rd, man/tm_g_butterfly.Rd, man/tm_g_events_term_id.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd, man/tm_g_spiderplot.Rd, man/tm_g_swimlane.Rd, man/tm_g_waterfall.Rd
Part of https://github.com/insightsengineering/teal.data/issues/333
Blocked by:
- https://github.com/insightsengineering/teal.code/pull/218
- https://github.com/insightsengineering/teal.data/pull/347
- https://github.com/insightsengineering/teal/pull/1402
=> `teal.data::datanames()` is deprecated in favor of dot-prefix and `names()`

R/teal.osprey.R, man/teal.osprey-package.Rd
Fixes #284 
I removed a link and resolved one manually to CRAN.
`R CMD check` doesn't complain (with 2024-12-07 r87428 ucrt).
Lintr didn't detect any issue
See https://github.com/insightsengineering/teal/issues/1420#issuecomment-2535506586 for a longer explanation.
=> Fix documentation note about links on r-devel

.github/workflows/scheduled.yaml, DESCRIPTION, man/tm_g_butterfly.Rd, man/tm_g_patient_profile.Rd, man/tm_g_spiderplot.Rd, man/tm_g_swimlane.Rd, man/tm_g_waterfall.Rd
Part of https://github.com/insightsengineering/nestdevs-tasks/issues/98
=> update packages versions for scheduled build

R/tm_g_ae_oview.R, R/tm_g_ae_sub.R, R/tm_g_butterfly.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_spiderplot.R, R/tm_g_swimlane.R, R/tm_g_waterfall.R, man/tm_g_ae_oview.Rd, man/tm_g_ae_sub.Rd, man/tm_g_butterfly.Rd, man/tm_g_events_term_id.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd, man/tm_g_spiderplot.Rd, man/tm_g_swimlane.Rd, man/tm_g_waterfall.Rd
https://github.com/insightsengineering/teal/issues/1441
Included `transformators` parameter in modules. This is passed to `teal::module` that does assertions and checks on this parameter.
=> 1441 Introduce transformators parameter in modules

.github/workflows/check.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml, .github/workflows/scheduled.yaml, DESCRIPTION
Part of https://github.com/insightsengineering/coredev-tasks/issues/609
From now on, we will provide development dependencies in 
```
Remotes: repo/project@branch
```
format, so it's explicitly visible in the DESCRIPTION file and can be handled by `pak::install`, `renv::install` and `remotes::install`.
With development dependencies specified in CJ Pipelines configuration, this connection was hidden, and it was hard to install the package from the main branch (or any other branch) locally from user's machine.
=> Remove lookup-refs, vbump dependencies + add Remotes

DESCRIPTION, NEWS.md, man/tm_g_ae_oview.Rd, man/tm_g_ae_sub.Rd, man/tm_g_butterfly.Rd, man/tm_g_events_term_id.Rd, man/tm_g_heat_bygrade.Rd, man/tm_g_patient_profile.Rd, man/tm_g_spiderplot.Rd, man/tm_g_swimlane.Rd, man/tm_g_waterfall.Rd
=> [skip vbump] upversion to 0.2.0

NEWS.md, R/tm_g_waterfall.R
=> update datanames in wf

R/tm_g_ae_oview.R, R/tm_g_ae_sub.R, R/tm_g_butterfly.R, R/tm_g_decorate.R, R/tm_g_events_term_id.R, R/tm_g_heat_bygrade.R, R/tm_g_patient_profile.R, R/tm_g_spiderplot.R, R/tm_g_swimlane.R, R/tm_g_waterfall.R
- Part of https://github.com/insightsengineering/teal/issues/1534
Companion to:
- https://github.com/insightsengineering/teal/pull/1592
- https://github.com/insightsengineering/teal.reporter/pull/401
Other similar PRs in modules:
- https://github.com/insightsengineering/teal.modules.clinical/pull/1425
- https://github.com/insightsengineering/teal.modules.general/pull/917
- https://github.com/insightsengineering/teal.goshawk/pull/366
- https://github.com/insightsengineering/teal.osprey/pull/319
=> Remove source code button from modules' encoding panel
